name: data-stats-models-ml
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.13
  - arviz
  - blackjax
  - duckdb
  - fastparquet
  - formulaic
  - graphviz
  - ipython
  - jax
  - jupyterlab
  - lightgbm
  - matplotlib
  - networkx
  - numpy
  - numpyro
  - nutpie
  - orjson
  - pandas
  - pandas-stubs
  - pandoc
  - polars
  - pyarrow
  - pymc
  - pyreadstat
  - pytorch
  - pyxlsb
  - scikit-learn
  - scipy
  - scipy-stubs
  - seaborn
  - shap
  - statsmodels
  - tabulate
  - xarray
  - xlrd
  - XlsxWriter
  - pip
